# Import

In [1]:
import os

os.chdir(os.path.dirname(os.path.abspath("")))

In [2]:
!pwd

/Users/alekpak/face_recognition_system


In [3]:
import torch
import skimage
import cv2
import torchvision


In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [5]:
torch.hub.list('NVIDIA/DeepLearningExamples:torchhub')

Using cache found in /Users/alekpak/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub
/Users/alekpak/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/PyTorch/Classification/ConvNets/image_classification/models/common.py:13: UserWarning: pytorch_quantization module not found, quantization will not be available
  warnings.warn(
/Users/alekpak/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/PyTorch/Classification/ConvNets/image_classification/models/efficientnet.py:17: UserWarning: pytorch_quantization module not found, quantization will not be available
  warnings.warn(


['nvidia_convnets_processing_utils',
 'nvidia_efficientnet',
 'nvidia_efficientnet_b0',
 'nvidia_efficientnet_b4',
 'nvidia_efficientnet_widese_b0',
 'nvidia_efficientnet_widese_b4',
 'nvidia_fastpitch',
 'nvidia_gpunet',
 'nvidia_hifigan',
 'nvidia_resneXt',
 'nvidia_resnet50',
 'nvidia_resnext101_32x4d',
 'nvidia_se_resnext101_32x4d',
 'nvidia_ssd',
 'nvidia_ssd_processing_utils',
 'nvidia_tacotron2',
 'nvidia_textprocessing_utils',
 'nvidia_tft',
 'nvidia_tft_data_utils',
 'nvidia_tts_utils',
 'nvidia_waveglow']

In [6]:
utils = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_ssd_processing_utils')

classes_to_labels = utils.get_coco_object_dictionary()

Using cache found in /Users/alekpak/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub


In [7]:
model = torchvision.models.detection.ssd300_vgg16(pretrained=True)
model.eval()

/Users/alekpak/face_recognition_system/.venv/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Users/alekpak/face_recognition_system/.venv/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=SSD300_VGG16_Weights.COCO_V1`. You can also use `weights=SSD300_VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


SSD(
  (backbone): SSDFeatureExtractorVGG(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace=True)
      (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (6): ReLU(inplace=True)
      (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (8): ReLU(inplace=True)
      (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace=True)
      (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (13): ReLU(inplace=True)
      (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (15): ReLU(inplace=

In [8]:
x = [torch.rand(3, 300, 300), torch.rand(3, 500, 400)]
x

[tensor([[[0.3118, 0.7859, 0.2504,  ..., 0.8646, 0.3893, 0.1694],
          [0.0456, 0.9568, 0.2494,  ..., 0.5763, 0.6789, 0.4064],
          [0.7755, 0.8879, 0.8561,  ..., 0.5580, 0.0636, 0.1507],
          ...,
          [0.3016, 0.8622, 0.8512,  ..., 0.8293, 0.1568, 0.9470],
          [0.7911, 0.2170, 0.8033,  ..., 0.7165, 0.8731, 0.6313],
          [0.6423, 0.3642, 0.8626,  ..., 0.0488, 0.8151, 0.6796]],
 
         [[0.0024, 0.7170, 0.0541,  ..., 0.9513, 0.0555, 0.1340],
          [0.7884, 0.7550, 0.0938,  ..., 0.8093, 0.1862, 0.5814],
          [0.9243, 0.5834, 0.6777,  ..., 0.3264, 0.6456, 0.1818],
          ...,
          [0.3279, 0.9755, 0.0760,  ..., 0.8140, 0.5045, 0.0106],
          [0.6990, 0.7508, 0.0205,  ..., 0.3917, 0.3000, 0.2822],
          [0.5184, 0.4632, 0.5707,  ..., 0.2599, 0.1777, 0.2489]],
 
         [[0.9030, 0.5610, 0.2032,  ..., 0.7292, 0.8533, 0.7868],
          [0.0416, 0.6533, 0.5672,  ..., 0.9257, 0.7762, 0.1160],
          [0.6004, 0.7357, 0.3717,  ...,

In [9]:
predictions = model(x)
predictions

[{'boxes': tensor([[6.9316e+01, 2.7528e+00, 2.5606e+02, 1.8082e+02],
          [6.8909e+01, 1.5694e+00, 2.2459e+02, 8.8590e+01],
          [3.6880e+01, 6.1005e+00, 1.8118e+02, 1.4391e+02],
          [4.2981e+01, 2.7996e+01, 1.1417e+02, 1.9129e+02],
          [6.2742e+00, 2.2341e+01, 8.3373e+01, 2.0084e+02],
          [1.0052e+01, 1.6212e+00, 1.5346e+02, 9.1541e+01],
          [1.0228e+02, 4.0176e+01, 2.1838e+02, 2.7378e+02],
          [3.2047e+00, 3.4794e+00, 2.9914e+02, 2.9364e+02],
          [1.3323e+02, 9.4133e+00, 2.1936e+02, 1.4586e+02],
          [1.3598e+01, 6.7772e+01, 1.3721e+02, 2.1374e+02],
          [7.9083e+01, 2.9916e+01, 1.4695e+02, 1.9074e+02],
          [9.9832e+01, 1.8972e+01, 1.7324e+02, 9.3486e+01],
          [7.8611e+01, 3.3703e+01, 2.1347e+02, 1.1891e+02],
          [1.6979e+02, 3.8207e+00, 2.4580e+02, 1.5836e+02],
          [1.0500e+01, 3.4955e-01, 2.9272e+02, 2.9774e+02],
          [1.0955e+02, 3.0726e+01, 1.7959e+02, 1.9290e+02],
          [1.2753e+00, 3.0346e+

In [10]:
image = cv2.imread('data/images.jpeg')
img = image.copy()
print(type(image))
imgtransform = torchvision.transforms.ToTensor()
image = imgtransform(image)
print(type(image))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [11]:
img

array([[[113,  99,  93],
        [113,  99,  93],
        [112,  98,  92],
        ...,
        [119,  97,  85],
        [119,  97,  85],
        [118,  96,  84]],

       [[ 62,  46,  40],
        [ 57,  44,  36],
        [ 54,  38,  32],
        ...,
        [ 35,  13,   1],
        [ 35,  13,   1],
        [ 35,  13,   1]],

       [[ 74,  56,  49],
        [ 73,  58,  49],
        [ 77,  59,  52],
        ...,
        [ 44,  23,   8],
        [ 44,  23,   8],
        [ 44,  23,   8]],

       ...,

       [[ 25,  21,  26],
        [ 24,  20,  25],
        [ 23,  20,  22],
        ...,
        [ 32,  23,  20],
        [ 32,  23,  20],
        [ 32,  23,  20]],

       [[ 25,  21,  26],
        [ 24,  20,  25],
        [ 23,  20,  22],
        ...,
        [ 32,  23,  20],
        [ 32,  23,  20],
        [ 32,  23,  20]],

       [[ 25,  21,  26],
        [ 24,  20,  25],
        [ 23,  20,  22],
        ...,
        [ 32,  23,  20],
        [ 32,  23,  20],
        [ 32,  23,  20]]

In [12]:
image

tensor([[[0.4431, 0.4431, 0.4392,  ..., 0.4667, 0.4667, 0.4627],
         [0.2431, 0.2235, 0.2118,  ..., 0.1373, 0.1373, 0.1373],
         [0.2902, 0.2863, 0.3020,  ..., 0.1725, 0.1725, 0.1725],
         ...,
         [0.0980, 0.0941, 0.0902,  ..., 0.1255, 0.1255, 0.1255],
         [0.0980, 0.0941, 0.0902,  ..., 0.1255, 0.1255, 0.1255],
         [0.0980, 0.0941, 0.0902,  ..., 0.1255, 0.1255, 0.1255]],

        [[0.3882, 0.3882, 0.3843,  ..., 0.3804, 0.3804, 0.3765],
         [0.1804, 0.1725, 0.1490,  ..., 0.0510, 0.0510, 0.0510],
         [0.2196, 0.2275, 0.2314,  ..., 0.0902, 0.0902, 0.0902],
         ...,
         [0.0824, 0.0784, 0.0784,  ..., 0.0902, 0.0902, 0.0902],
         [0.0824, 0.0784, 0.0784,  ..., 0.0902, 0.0902, 0.0902],
         [0.0824, 0.0784, 0.0784,  ..., 0.0902, 0.0902, 0.0902]],

        [[0.3647, 0.3647, 0.3608,  ..., 0.3333, 0.3333, 0.3294],
         [0.1569, 0.1412, 0.1255,  ..., 0.0039, 0.0039, 0.0039],
         [0.1922, 0.1922, 0.2039,  ..., 0.0314, 0.0314, 0.

In [13]:
image.unsqueeze(0)

tensor([[[[0.4431, 0.4431, 0.4392,  ..., 0.4667, 0.4667, 0.4627],
          [0.2431, 0.2235, 0.2118,  ..., 0.1373, 0.1373, 0.1373],
          [0.2902, 0.2863, 0.3020,  ..., 0.1725, 0.1725, 0.1725],
          ...,
          [0.0980, 0.0941, 0.0902,  ..., 0.1255, 0.1255, 0.1255],
          [0.0980, 0.0941, 0.0902,  ..., 0.1255, 0.1255, 0.1255],
          [0.0980, 0.0941, 0.0902,  ..., 0.1255, 0.1255, 0.1255]],

         [[0.3882, 0.3882, 0.3843,  ..., 0.3804, 0.3804, 0.3765],
          [0.1804, 0.1725, 0.1490,  ..., 0.0510, 0.0510, 0.0510],
          [0.2196, 0.2275, 0.2314,  ..., 0.0902, 0.0902, 0.0902],
          ...,
          [0.0824, 0.0784, 0.0784,  ..., 0.0902, 0.0902, 0.0902],
          [0.0824, 0.0784, 0.0784,  ..., 0.0902, 0.0902, 0.0902],
          [0.0824, 0.0784, 0.0784,  ..., 0.0902, 0.0902, 0.0902]],

         [[0.3647, 0.3647, 0.3608,  ..., 0.3333, 0.3333, 0.3294],
          [0.1569, 0.1412, 0.1255,  ..., 0.0039, 0.0039, 0.0039],
          [0.1922, 0.1922, 0.2039,  ..., 0

In [14]:
ypred = model([image])
print(ypred[0].keys())

dict_keys(['boxes', 'scores', 'labels'])


In [17]:
ypred

[{'boxes': tensor([[1.9717e+02, 5.1190e+01, 2.5244e+02, 1.5654e+02],
          [1.2638e+02, 4.2068e+01, 1.8553e+02, 1.9700e+02],
          [1.5510e+02, 4.5044e+01, 1.9516e+02, 1.5783e+02],
          [1.0226e+02, 9.7773e+01, 1.1228e+02, 1.2304e+02],
          [1.9179e+01, 1.2904e+02, 4.5174e+01, 1.5631e+02],
          [8.2038e-01, 1.2647e+02, 1.4853e+02, 1.9323e+02],
          [8.6757e+01, 5.2502e+01, 1.3276e+02, 1.0169e+02],
          [1.5693e+02, 1.7614e+02, 2.1480e+02, 1.9350e+02],
          [1.7325e+02, 1.5639e+02, 2.1981e+02, 1.7426e+02],
          [1.5804e+02, 4.7961e+01, 1.8950e+02, 1.0652e+02],
          [1.6004e+02, 1.6237e+02, 2.1475e+02, 1.8237e+02],
          [6.9545e+01, 1.3035e+02, 1.3210e+02, 1.7883e+02],
          [2.7426e+01, 1.5470e+02, 1.0225e+02, 1.9567e+02],
          [1.1303e+02, 4.2507e+01, 1.8605e+02, 1.0779e+02],
          [1.4761e+02, 4.3783e+01, 2.2764e+02, 1.7602e+02],
          [1.2547e+02, 4.3318e+01, 1.5900e+02, 7.8899e+01],
          [2.3036e+00, 1.0951e+

In [ ]:
bbox,scores,labels = ypred[0]['boxes'],ypred[0]['scores'],ypred[0]['labels']
nums = torch.argwhere(scores > 0.80).shape[0]
nums

2

In [ ]:
for i in range(nums):
        x,y,w,h = bbox[i].numpy().astype('int')
        cv2.rectangle(img,(x,y),(w,h),(0,0,255),5)
        classname = labels[i].numpy().astype('int')
        classdetected = classes_to_labels[classname-1]
        

cv2.imshow('frame',img)
cv2.waitKey(0)

113

In [15]:
classdetected

'person'

In [ ]:
def detect_people(image):
    transform = torchvision.transforms.Compose([
        torchvision.transforms.ToTensor(),
    ])
    
    image_tensor = transform(image).float()
    image_tensor = image_tensor.unsqueeze(0)

    with torch.no_grad():
        detections = model(image_tensor)

    return detections[0]